apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com:konstructio/manifests.git/argocd/demo?ref=v1.1.0

generatorOptions:
  disableNameSuffixHash: true
