apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: colony
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster 
    namespace: tink-system
  source:
    chart: colony
    repoURL: https://charts.konstruct.io
    targetRevision: 0.1.0
    helm:
      releaseName: colony
      values: |
        colony-agent:
          extraEnv:
            COLONY_API_URL: https://colony-api-virtual.konstruct.io
            LOAD_BALANCER: 10.90.14.2
            TALOS_URL_FILES_SOURCE: http://10.90.14.2:8080
          extraEnvSecrets:
            API_TOKEN:
              key: api-key
              name: colony-api
  syncPolicy:
    # automated:
    #   prune: true
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
