apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tink-stack-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/k3s-datacenter.git
    path: registry/laptop/tink-stack
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: tink-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
