apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tink-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  destination:
    name: in-cluster 
    namespace: tink-system
  source:
    chart: stack
    repoURL: ghcr.io/tinkerbell/charts
    targetRevision: 0.4.4
    helm:
      releaseName: tink-stack
      values: |
        global:
          # publicIP is used to set what both smee.publicIP and stack.loadBalancerIP do individually.
          publicIP: 10.90.14.2
        hegel:
          trustedProxies:
          - 10.42.0.0/24
        smee:
          image: public.ecr.aws/kubefirst/smee:9371956
          trustedProxies:
          - 10.42.0.0/24
          tftp:
            timeout: 120s
          additionalArgs:
            - -dhcp-auto-discovery=true
            - -dhcp-mode=proxy
        stack:
          kubevip:
            interface: enp3s0
          relay:
            sourceInterface: enp3s0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
