apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tink-stack
  namespace: tink-system
spec:
  repo: ghcr.io/tinkerbell/charts
  chart: stack
  targetNamespace: tink-system
  valuesContent: |-
    # 0.5.0 required for global.
    # global:
    #   # publicIP is used to set what both smee.publicIP and stack.loadBalancerIP do individually.
    #   publicIP: 10.90.14.2
    hegel:
      trustedProxies:
      - 10.42.0.0/24
    smee:
      publicIP: 10.90.14.2
      image: public.ecr.aws/kubefirst/smee:9371956
      trustedProxies:
      - 10.42.0.0/24
      tftp:
        timeout: 120s
      additionalArgs:
        - -dhcp-auto-discovery=true
        - -dhcp-mode=proxy
    stack:
      loadBalancerIP: 10.90.14.2
      kubevip:
        interface: enp3s0
      relay:
        sourceInterface: enp3s0
